"use client";
import { useMemo, useState } from "react";
import { toolCategories, type Tool, type ToolCategory } from "@/data/tools";
import { ToolCard } from "./ToolCard";
import { AdSlot } from "./AdSlot";

export function ToolExplorer({ tools, mode = "home" }: { tools: Tool[]; mode?: "home" | "catalog" }) {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState<ToolCategory | "all">("all");
  const matches = useMemo(() => { const term = query.trim().toLocaleLowerCase(); return tools.filter((tool) => (category === "all" || tool.category === category) && (!term || [tool.name, tool.description, tool.shortDescription, tool.category, ...tool.keywords].join(" ").toLocaleLowerCase().includes(term))); }, [tools, query, category]);
  const popular = tools.filter((tool) => tool.popularityRank).sort((a, b) => (a.popularityRank ?? 99) - (b.popularityRank ?? 99)).slice(0, 5);
  const select = (value: ToolCategory | "all") => { setCategory(value); if (mode === "home") document.getElementById("todas-las-herramientas")?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  return <><section className="toolsHero" aria-labelledby="tools-title"><p>HERRAMIENTAS ONLINE PARA TODOS</p><h1 id="tools-title">HYGROUNDD <span>TOOLS</span></h1><h2>Herramientas gratuitas. Simples. Rápidas. Sin complicaciones.</h2><label className="toolSearch" id="tools-search"><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar una herramienta..." aria-label="Buscar una herramienta" /></label><div className="categoryChips" role="group" aria-label="Filtrar por categoría"><button className={category === "all" ? "isActive" : ""} onClick={() => select("all")}>Todas</button>{toolCategories.map((item) => <button className={category === item.id ? "isActive" : ""} onClick={() => select(item.id)} key={item.id}>{item.label}</button>)}</div></section>
    {mode === "home" ? <><section className="toolsSection"><div className="toolsHeading"><div><p>LO MÁS USADO</p><h2>Más populares</h2><span>Las 5 herramientas más utilizadas por nuestra comunidad.</span></div></div><div className="popularGrid">{popular.map((tool) => <ToolCard tool={tool} rank={tool.popularityRank} key={`${tool.category}-${tool.id}`} />)}</div></section><AdSlot placement="home-after-popular" /><section className="toolsSection" id="categorias"><div className="toolsHeading"><div><p>ENCUENTRA LO QUE NECESITAS</p><h2>Explora por categorías</h2></div></div><div className="categoryGrid">{toolCategories.map((item) => { const count = tools.filter((tool) => tool.category === item.id).length; return <button className={`categoryCard categoryCard--${item.color}`} onClick={() => select(item.id)} key={item.id}><span>{item.label.slice(0, 3).toUpperCase()}</span><strong>{item.label}</strong><small>{count} herramientas</small><i>→</i></button>; })}</div></section><AdSlot placement="home-after-categories" /></> : null}
    <section className="toolsSection toolsCatalog" id="todas-las-herramientas"><div className="toolsHeading"><div><p>{mode === "home" ? "CATÁLOGO" : "TODAS LAS HERRAMIENTAS"}</p><h2>{query || category !== "all" ? "Resultados" : "Todas las herramientas"}</h2><span>{matches.length} herramientas encontradas</span></div></div>{matches.length ? <div className="toolGrid">{matches.map((tool) => <ToolCard tool={tool} key={`${tool.category}-${tool.id}`} />)}</div> : <p className="toolEmpty">No encontramos herramientas con esa búsqueda.</p>}</section>
  </>;
}
