import Link from "next/link";
import { AdSlot } from "@/components/tools/AdSlot";
import { ToolAsset } from "@/components/tools/ToolAsset";
import type { ToolUi } from "@/data/tool-ui";

function UploadZone({ formats = ["Archivo", "Máximo 25 MB"] }: { formats?: string[] }) { return <div className="toolUpload"><span className="toolUpload__mark">↑</span><strong>Arrastra tu archivo aquí</strong><small>o</small><button type="button" className="toolSecondary" disabled>Seleccionar archivo · Próximamente</button><em>{formats.join(" · ")}</em></div>; }
function Options({ children }: { children: React.ReactNode }) { return <aside className="toolOptions"><p>OPCIONES</p>{children}</aside>; }
const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="toolField"><span>{label}</span>{children}</label>;

export function ToolPage({ tool }: { tool: ToolUi }) {
  const workspace = tool.kind === "text" ? <><textarea className="toolTextarea" placeholder="Escribe o pega tu texto aquí…" /><div className="toolMetrics">{["Palabras", "Caracteres", "Sin espacios", "Oraciones", "Párrafos", "Tiempo lectura"].map((item) => <div key={item}><strong>—</strong><span>{item}</span></div>)}</div></>
    : tool.kind === "password" ? <div className="toolFormLayout"><div><div className="toolOutput"><span>Tu contraseña aparecerá aquí</span><button type="button" disabled>Copiar</button></div><Field label="LONGITUD"><input type="range" min="8" max="32" defaultValue="16" /></Field></div><Options><label><input type="checkbox" defaultChecked /> Mayúsculas</label><label><input type="checkbox" defaultChecked /> Minúsculas</label><label><input type="checkbox" defaultChecked /> Números</label><label><input type="checkbox" /> Símbolos</label><b className="toolStrength">FUERTE</b></Options></div>
    : tool.kind === "qr" ? <div className="toolFormLayout"><Field label="TEXTO O URL"><textarea className="toolTextarea toolTextarea--small" placeholder="https://…" /></Field><div className="qrPlaceholder">QR<br /><small>VISTA PREVIA</small></div><Options><Field label="TAMAÑO"><select defaultValue="512"><option value="256">256 px</option><option value="512">512 px</option><option value="1024">1024 px</option></select></Field><Field label="FORMATO"><select><option>PNG</option><option>SVG</option></select></Field></Options></div>
    : tool.kind === "percentage" ? <div className="percentageGrid">{[["¿Cuánto es X% de Y?", "Porcentaje", "Valor"], ["X es qué porcentaje de Y?", "Valor X", "Valor Y"], ["Aumentar/disminuir X%", "Valor", "Porcentaje"]].map(([title, one, two]) => <div className="percentageCase" key={title}><h2>{title}</h2><input placeholder={one} inputMode="decimal" /><input placeholder={two} inputMode="decimal" /><output>Resultado próximamente</output></div>)}</div>
    : <div className="toolFormLayout"><UploadZone formats={tool.formats} />{tool.kind === "images" ? <Options><Field label="TAMAÑO DE PÁGINA"><select><option>A4</option><option>Carta</option></select></Field><Field label="ORIENTACIÓN"><select><option>Vertical</option><option>Horizontal</option></select></Field><Field label="MARGEN"><select><option>Normal</option><option>Estrecho</option></select></Field></Options> : tool.kind === "image-convert" ? <Options><Field label="FORMATO DE SALIDA"><select><option>{tool.slug === "jpg-to-png" ? "PNG" : "JPG"}</option></select></Field><Field label="CALIDAD"><select><option>Alta</option><option>Recomendada</option></select></Field></Options> : <Options><Field label={tool.slug === "compress-pdf" ? "NIVEL" : tool.slug === "pdf-to-images" ? "FORMATO" : "SALIDA"}><select><option>Recomendada</option><option>Alta calidad</option><option>Máxima compresión</option></select></Field><p className="toolOptionNote">Los ajustes se habilitarán cuando el procesamiento esté disponible.</p></Options>}</div>;
  return <><section className="toolPageHero"><Link href="/tools" className="toolBreadcrumb">Herramientas <span>›</span> {tool.category}</Link><ToolAsset asset={tool.asset} className="toolPageHero__asset" /><p>{tool.category}</p><h1>{tool.name}</h1><span>{tool.description}</span></section><section className="toolWorkspace"><div className="toolWorkspace__top"><span>ESPACIO DE TRABAJO</span><b>BETA UI</b></div>{workspace}</section><AdSlot placement="tool-before-action" /><section className="toolActionRow"><div><strong>Disponible próximamente</strong><span>Esta herramienta aún no procesa archivos ni genera resultados.</span></div><button className="toolPrimary" disabled>{tool.kind === "qr" ? "Generar QR" : "Procesar"} · Próximamente</button></section><section className="toolRelated"><p>OTRAS HERRAMIENTAS</p><Link href="/tools">Explorar el catálogo <span>→</span></Link></section></>;
}
